language: node_js
node_js:
  - "6.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

after_success:
  - npm run build
  - firebase deploy --token=${FIREBASE_API_TOKEN}
